### ISSUE TITLE
API v2 is not implemented.

### ISSUE THREAD

**Issue by philipperemy** [unwitting/bitstampy#12]
https://www.bitstamp.net/api/

BUY LIMIT ORDER

At the moment cannot give the `currency_pair` param. For now we can only trade BTC/USD.

**Comment by AdityaNayak** [comment]
+1

Any timelines on this? I am willing to contribute if you are not actively maintaining this.

**Comment by unwitting** [comment]
Happy to accept MRs, I'm not actively maintaining right now. Have historically accepted MRs that bring this library up to speed with changes to Bitstamp's API, and deployed to PyPi :)

**Comment by unwitting** [comment]
Closing with a bump for above comment - MRs are welcome but I don't actively maintain :) you may have more luck amongst the forks of this repo.
