### ISSUE TITLE
ImportError on Python 3.5

### ISSUE THREAD

**Issue by johan-bjareholt** [unwitting/bitstampy#6]
When trying to do 'from bistampy import api' i get 'ImportError: No module named calls'

A simple fix for this was to simply change the first line in api.py from 'import calls' to 'from . import calls'

**Comment by unwitting** [comment]
Nice, feel free to create a PR :) need to make sure it works fine in Python 2, still.

**Comment by johan-bjareholt** [comment]
Created a pr :)

https://github.com/unwitting/bitstampy/pull/7

**Comment by unwitting** [comment]
Cheers!
